# Generated by Django 3.1 on 2020-09-05 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.CharField(blank=True, default=' ', help_text='관련종목', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.PROTECT, related_name='my_article', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
