# Generated by Django 3.1 on 2020-09-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200905_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='proto',
            field=models.TextField(blank=True, default=' ', help_text='해당 프로토 아티클'),
        ),
        migrations.AddField(
            model_name='article',
            name='relate_dart',
            field=models.TextField(blank=True, default=' ', help_text='관련자료 id. , 로 구분'),
        ),
    ]
